In [ ]:
import pandas as pd
df = pd.read_csv("course_data.csv")

In [ ]:
df.head()

,course_id,course_title,url,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject,profit,published_date,published_time,year,month,day
0,1070968,Ultimate Investment Banking Course,https://www.udemy.com/ultimate-investment-bank...,True,200,2147,23,51,All Levels,1.5 hours,2017-01-18T20:58:58Z,Business Finance,429400,2017-01-18,20:58:58Z,2017,1,18
1,1113822,Complete GST Course & Certification - Grow You...,https://www.udemy.com/goods-and-services-tax/,True,75,2792,923,274,All Levels,39 hours,2017-03-09T16:34:20Z,Business Finance,209400,2017-03-09,16:34:20Z,2017,3,9
2,1006314,Financial Modeling for Business Analysts and C...,https://www.udemy.com/financial-modeling-for-b...,True,45,2174,74,51,Intermediate Level,2.5 hours,2016-12-19T19:26:30Z,Business Finance,97830,2016-12-19,19:26:30Z,2016,12,19
3,1210588,Beginner to Pro - Financial Analysis in Excel ...,https://www.udemy.com/complete-excel-finance-c...,True,95,2451,11,36,All Levels,3 hours,2017-05-30T20:07:24Z,Business Finance,232845,2017-05-30,20:07:24Z,2017,5,30
4,1011058,How To Maximize Your Profits Trading Options,https://www.udemy.com/how-to-maximize-your-pro...,True,200,1276,45,26,Intermediate Level,2 hours,2016-12-13T14:57:18Z,Business Finance,255200,2016-12-13,14:57:18Z,2016,12,13

In [ ]:
df.shape

(3683, 18)

In [ ]:
df.isnull().sum()

course_id              0
course_title           0
url                    0
is_paid                0
price                  0
num_subscribers        0
num_reviews            0
num_lectures           0
level                  0
content_duration       0
published_timestamp    0
subject                0
profit                 0
published_date         0
published_time         1
year                   0
month                  0
day                    0
dtype: int64

In [ ]:
df["published_time"].fillna( method ='ffill', inplace = True)

In [ ]:
df.isnull().sum()

course_id              0
course_title           0
url                    0
is_paid                0
price                  0
num_subscribers        0
num_reviews            0
num_lectures           0
level                  0
content_duration       0
published_timestamp    0
subject                0
profit                 0
published_date         0
published_time         0
year                   0
month                  0
day                    0
dtype: int64

In [ ]:
df.duplicated().sum()

6

In [ ]:
df.columns

Index(['course_id', 'course_title', 'url', 'is_paid', 'price',
       'num_subscribers', 'num_reviews', 'num_lectures', 'level',
       'content_duration', 'published_timestamp', 'subject', 'profit',
       'published_date', 'published_time', 'year', 'month', 'day'],
      dtype='object')

In [ ]:
df.drop(['course_id','published_timestamp','published_time','month','day','published_date','profit','year'],axis=1, inplace=True)

In [ ]:
df.head()

,course_title,url,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,subject
0,Ultimate Investment Banking Course,https://www.udemy.com/ultimate-investment-bank...,True,200,2147,23,51,All Levels,1.5 hours,Business Finance
1,Complete GST Course & Certification - Grow You...,https://www.udemy.com/goods-and-services-tax/,True,75,2792,923,274,All Levels,39 hours,Business Finance
2,Financial Modeling for Business Analysts and C...,https://www.udemy.com/financial-modeling-for-b...,True,45,2174,74,51,Intermediate Level,2.5 hours,Business Finance
3,Beginner to Pro - Financial Analysis in Excel ...,https://www.udemy.com/complete-excel-finance-c...,True,95,2451,11,36,All Levels,3 hours,Business Finance
4,How To Maximize Your Profits Trading Options,https://www.udemy.com/how-to-maximize-your-pro...,True,200,1276,45,26,Intermediate Level,2 hours,Business Finance

In [ ]:
!pip install gradientai --upgrade

Collecting gradientai
  Downloading gradientai-1.12.1-py3-none-any.whl (386 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 386.3/386.3 kB 4.7 MB/s eta 0:00:00
Collecting aenum>=3.1.11 (from gradientai)
  Downloading aenum-3.1.15-py3-none-any.whl (137 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 137.6/137.6 kB 21.3 MB/s eta 0:00:00
Collecting pydantic<2.0.0,>=1.10.5 (from gradientai)
  Downloading pydantic-1.10.15-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 37.7 MB/s eta 0:00:00
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from gradientai) (2.8.2)
Requirement already satisfied: urllib3>=1.25.3 in /usr/local/lib/python3.10/dist-packages (from gradientai) (2.0.7)
Requirement already satisfied: typing-extensions>=4.2.0 in /usr/local/lib/python3.10/dist-packages (from pydantic<2.0.0,>=1.10.5->gradientai) (4.11.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->gradientai) (1.16.0)
Installing collected packages: aenum, pydantic, gradientai
  Attempting uninstall: pydantic
    Found existing installation: pydantic 2.7.1
    Uninstalling pydantic-2.7.1:
      Successfully uninstalled pydantic-2.7.1
Successfully installed aenum-3.1.15 gradientai-1.12.1 pydantic-1.10.15

In [ ]:
import pandas as pd
import numpy as np
import os
import sys
import csv
from gradientai import Gradient

In [ ]:
from functools import total_ordering
os.environ['GRADIENT_ACCESS_TOKEN'] = "<YOUR_GRADIENTAI_ACCESS_TOKEN>"
os.environ['GRADIENT_WORKSPACE_ID'] = "<YOUR_GRADIENTAI_WORKSPACE_ID>"

course_dataset_path = "course_data.csv"
## intialize the gradient
gradient = Gradient()

print("## Loading the data.....")
formatted_data = []
with open(course_dataset_path, encoding='utf-8-sig') as f:
  dataset_data = csv.DictReader(f, delimiter=",")
  for row in dataset_data:
    user_data = f"Is Paid: {row['is_paid']}, Price: {row['price']}, Number of Suscribers: {row['num_subscribers']}, num_reviews: {row['num_reviews']}, num_lectures: {row['num_lectures']}, level: {row['level']}, content_duration: {row['content_duration']}, subject: {row['subject']}"
    course_response = row['course_title']
    course_url = row['url']
    formatted_entry = {
        "inputs": f"### User Data:\n{user_data}\n\n### Suggested Course Name:",
        "response": f"{course_response} with the link: {course_url}"
    }
    formatted_data.append(formatted_entry)

base = gradient.get_base_model(base_model_slug="llama2-7b-chat")
new_model_adapter = base.create_model_adapter(name='ai_course_chat_bot')

print("Fine Tuning the model.......")
chunk_lines = 150 # SET ACCORDING TO YOU
total_chunks = [formatted_data[x:x+chunk_lines] for x in range(0, len(formatted_data), chunk_lines)]
for i, chunk in enumerate(total_chunks):
  try:
    print(f"Fine Tuning chunk {i+1} of {len(total_chunks)}")
    new_model_adapter.fine_tune(samples=chunk)
  except Exception as error:
    print(f"Error occured in fine tuning {i+1}: {error}")

In [ ]:
data.head()

,Unnamed: 0,course_title,url,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,subject
0,0,Ultimate Investment Banking Course,https://www.udemy.com/ultimate-investment-bank...,True,200,2147,23,51,All Levels,1.5 hours,Business Finance
1,1,Complete GST Course & Certification - Grow You...,https://www.udemy.com/goods-and-services-tax/,True,75,2792,923,274,All Levels,39 hours,Business Finance
2,2,Financial Modeling for Business Analysts and C...,https://www.udemy.com/financial-modeling-for-b...,True,45,2174,74,51,Intermediate Level,2.5 hours,Business Finance
3,3,Beginner to Pro - Financial Analysis in Excel ...,https://www.udemy.com/complete-excel-finance-c...,True,95,2451,11,36,All Levels,3 hours,Business Finance
4,4,How To Maximize Your Profits Trading Options,https://www.udemy.com/how-to-maximize-your-pro...,True,200,1276,45,26,Intermediate Level,2 hours,Business Finance

In [ ]:
user_query = "Is Paid: True, Price: 75, Number of Suscribers: 2792, num_reviews: 923, num_lectures: 274, level: 	All Levels, content_duration: 39, subject: Business Finance"
formatted_query = f"### User Data:\n{user_query}\n\n### Suggested Course Name:"
response = new_model_adapter.complete(query=formatted_query, max_generated_token_count=50)
print(f"> {user_query}\n {response.generated_output}")

> Is Paid: True, Price: 75, Number of Suscribers: 2792, num_reviews: 923, num_lectures: 274, level: 	All Levels, content_duration: 39, subject: Business Finance
  Based on the user data provided, here are some suggested course names for the course you described:

1. "Financial Mastery: Essential Skills for Business Success"
2. "Business Finance Pro: Mastering